CREATE TABLE CLIENT(
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE GYM(
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	address TEXT NOT NULL
);

CREATE TABLE MODALITY(
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE CLIENT_GYM(
	id INTEGER PRIMARY KEY,
	client_id INTEGER,
	gym_id INTEGER NOT NULL,
	FOREIGN KEY (client_id) 
		REFERENCES CLIENT (id) 
			ON DELETE RESTRICT 
			ON UPDATE NO ACTION,
	FOREIGN KEY (gym_id) 
		REFERENCES GYM (id)
			ON DELETE RESTRICT 
			ON UPDATE NO ACTION
);

CREATE TABLE GYM_MODALITY(
	id INTEGER PRIMARY KEY,
	gym_id INTEGER NOT NULL,
	modality_id INTEGER NOT NULL,
	FOREIGN KEY (gym_id) 
		REFERENCES GYM (id)
			ON DELETE RESTRICT 
			ON UPDATE NO ACTION,
	FOREIGN KEY (modality_id) 
		REFERENCES MODALITY (id) 
			ON DELETE RESTRICT 
			ON UPDATE NO ACTION
);

CREATE TABLE CLIENT_MODALITY(
	id INTEGER PRIMARY KEY,
	client_id INTEGER,
	modality_id INTEGER NOT NULL,
	FOREIGN KEY (client_id) 
		REFERENCES CLIENT (id) 
			ON DELETE RESTRICT 
			ON UPDATE NO ACTION,
	FOREIGN KEY (modality_id) 
		REFERENCES MODALITY (id) 
			ON DELETE RESTRICT 
			ON UPDATE NO ACTION
);